version: '2'

services:
  customers:
    image: customers    
    build:
      context: ./Customers/publish
      dockerfile: Dockerfile
    ports:
      - "80:5001"

  api_gateway:
    image: api_gateway
    build:
      context: ./API_Gateway/publish
      dockerfile: Dockerfile
    ports:
      - "80:5000"

  

  orders:
    image: orders
    build:
      context: ./Orders/publish
      dockerfile: Dockerfile
    ports:
      - "80:5002"
 