version: '2'

services:
  customers:
    image: customers    
    build:
      context: ./Customers
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  api_gateway:
    image: api_gateway
    build:
      context: ./API_Gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  

  orders:
    image: orders
    build:
      context: ./Orders
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
 