version: '2'

services:
  customers:
    image: customers    
    build:
      context: ./Customers
      dockerfile: Dockerfile
    ports:
      - "5001:5001"    
    networks: 
      - enterprise-planner-network

  api_gateway:
    image: api_gateway
    build:
      context: ./API_Gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    links:
      - customers
      - orders
    networks: 
      - enterprise-planner-network
  

  orders:
    image: orders
    build:
      context: ./Orders
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    networks: 
      - enterprise-planner-network
    
  message_broker:
    image: rabbitmq:3-management
    ports: 
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret cookie'
    links:
      - customers
      - orders
    networks: 
      - enterprise-planner-network
 
networks:
  enterprise-planner-network:
    driver: bridge
