version: '2'

services:
  customers:
    image: customers
    build:
      context: ./Customers
      dockerfile: Dockerfile

  orders:
    image: orders
    build:
      context: ./Orders
      dockerfile: Dockerfile
  api_gateway:
    image: api_gateway
    build:
      context: ./API_Gateway
      dockerfile: Dockerfile
