version: '2'

services:
  customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
